version: 3.0.504.{build}

branches:
# whitelist
    only:
        - '3.0'
        - appveyor

install:
    - git submodule -q update --init

build:
    project: msvs\RedisServer.sln
after_build:
- cmd: 7z a redis-server.zip c:\projects\redis\msvs\x64\Release\redis-server.exe

artifacts:
- path: '**\redis*.zip'
  name: RedisServer
